### ISSUE TITLE
Proxy Issue

### ISSUE THREAD

**Issue by M-Kleinschmidt** [MarcoCiaramella/cpu-web-miner#16]
Hello everyone,

first of all I would like to say that I have already successfully tested the cpu-web-miner and I am very pleased. As far as I could see, every new website visitor is a single connection to the mining pool and will not be bundled by your backend. This is not a problem with a small number of visitors, but with too many it can result in a wallet ban from the mining pool. That's why I wanted to use a stratum mining proxy. While searching for a proxy that supports ghostrider, I came across Ultimate Proxy ([https://github.com/romslf/Ultimate-Proxy](https://github.com/romslf/Ultimate-Proxy)). I then installed it on a new VM and tried to connect, but got the following error message:
```
[11:52:34AM] [SmartSwitch] Disabled.
[11:52:34AM] Logging queue started
[11:52:34AM] [RatioSwitch] Disabled.
[11:52:34AM] Proxy server starting...
[11:52:34AM] Proxy server started successfully.
[11:52:34AM] Listening on: 127.0.0.1:4444, 127.0.1.1:4444, xxx.xxx.xxx.xxx:4444, xxxx::9400:3ff:febf:xxxa%2:4444
[11:52:34AM] Waiting for a connection...
[11:52:34AM] Stratum variables reset
[11:52:34AM] Stratum variables reset
[11:52:34AM] [POOL] Starting RTM pool mining ...
[11:52:34AM] [POOL] Server Name: ghostrider.eu.mine.zpool.ca
[11:52:34AM] [POOL] ghostrider.eu.mine.zpool.ca connection established.
[11:52:35AM] [POOL] Sent packet to POOL: {"id":1,"method":"mining.subscribe","params":["UltimateProxy/2.4.4.4"]}

[11:52:35AM] [POOL] Sent packet to POOL: {"id":2,"method":"mining.authorize","params":["pqx5ej6z9cvxc2c7nw5p4s5kf8nzmzc5cqapu8xprq.UltimateProxy","c=BCH"]}

[11:52:35AM] Sever message: {"id":1,"result":[[["mining.set_difficulty","0.020"],["mining.notify","3effd75834feb07d1c9fac1d61c2b3a1"]],"600d150c",4],"error":null}
[11:52:35AM] UltimateProxy subscribed to pool successfully.
[11:52:35AM] Sever message: {"id":2,"result":true,"error":null}
[11:52:35AM] UltimateProxy authorized by pool successfully.
[11:52:35AM] Sever message: {"id":null,"method":"mining.set_difficulty","params":[0.020]}
[11:52:35AM] [POOL] Difficulty set to 85.901Mh
[11:52:35AM] Sever message: {"id":null,"method":"mining.notify","params":["1b4d","9ca69ded1544e2a65458cfda68419c10a217fda06e1edf8aa5f157556de03062","03000500010000000000000000000000000000000000000000000000000000000000000000ffffffff1d0383cd09046885fe6608","2f7a706f6f6c2e63612f000000000003001edc0c170000001976a91460cea3490e0c5ab9b1de7cb07d8e6ce24912c8c288ac800737c3050000001976a9144cd64d41e1201ea101b0e6838d3e89156ccd1ca688ac80703970560000001976a91418f167b74201c6388ead97c2dc4a9fa50348caf188ac0000000046020083cd0900300e660a402b86f0b2375ae235527272798af76fa98fd9c6a92cc0059a53cef42e630fedc929253f73074a1fb7e19962c417a5b230945ab7d7207585b167908a",["6eb3af9bb40d4b1ac881624676f1e1d277982d636a545b9bd21aead269d53de6","50617e4b337e86ac8f0e3023fe1e7c287ea2cf41c4f056ee593c20531f93135f"],"20000000","1e00b062","66fe8568",true]}
[11:52:44AM] Sever message: {"id":null,"method":"mining.notify","params":["1b5c","9ca69ded1544e2a65458cfda68419c10a217fda06e1edf8aa5f157556de03062","03000500010000000000000000000000000000000000000000000000000000000000000000ffffffff1d0383cd09048c85fe6608","2f7a706f6f6c2e63612f0000000000032e1edc0c170000001976a91460cea3490e0c5ab9b1de7cb07d8e6ce24912c8c288ac8b0737c3050000001976a9144cd64d41e1201ea101b0e6838d3e89156ccd1ca688ac30713970560000001976a91418f167b74201c6388ead97c2dc4a9fa50348caf188ac0000000046020083cd0900300e660a402b86f0b2375ae235527272798af76fa98fd9c6a92cc0059a53cef42e630fedc929253f73074a1fb7e19962c417a5b230945ab7d7207585b167908a",["6eb3af9bb40d4b1ac881624676f1e1d277982d636a545b9bd21aead269d53de6","8a5a36f5fedcb4371ad94a6a7426fa96dd8b07e069b5720ce776597d27ec25f3"],"20000000","1e00b062","66fe858c",true]}
[11:53:09AM] Stratum OnClientMessage: Packet from slave: {"id": "mining.subscribe", "method": "mining.subscribe", "params": [""]}
[11:53:09AM] Worker 206.189.53.131:56628 disconnected.
[11:53:09AM] Nonce c2 released.
[11:53:09AM] Stratum OnClientMessage: Newtonsoft.Json.JsonSerializationException: Error converting value "mining.subscribe" to type 'System.Int64'. Path 'id', line 1, position 25.
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus , TypeCode )
   at System.Number.ParseInt64(ReadOnlySpan`1 , NumberStyles , NumberFormatInfo )
   at System.Int64.Parse(String s, IFormatProvider provider)
   at System.Convert.ToInt64(String value, IFormatProvider provider)
   at System.String.System.IConvertible.ToInt64(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at UltimateProxyV2.CoinHandlers.Stratum.OnClientMessage(Slave slave, String req)
[11:53:09AM] Waiting for a connection...
[11:53:09AM] Stratum OnClientMessage: Packet from slave: {"id": "mining.subscribe", "method": "mining.subscribe", "params": [""]}
[11:53:09AM] Worker 206.189.53.131:56642 disconnected.
[11:53:09AM] Nonce 77 released.
[11:53:09AM] Stratum OnClientMessage: Newtonsoft.Json.JsonSerializationException: Error converting value "mining.subscribe" to type 'System.Int64'. Path 'id', line 1, position 25.
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus , TypeCode )
   at System.Number.ParseInt64(ReadOnlySpan`1 , NumberStyles , NumberFormatInfo )
   at System.Int64.Parse(String s, IFormatProvider provider)
   at System.Convert.ToInt64(String value, IFormatProvider provider)
   at System.String.System.IConvertible.ToInt64(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at UltimateProxyV2.CoinHandlers.Stratum.OnClientMessage(Slave slave, String req)
[11:53:09AM] Waiting for a connection...
[11:53:09AM] Stratum OnClientMessage: Packet from slave: {"id": "mining.subscribe", "method": "mining.subscribe", "params": [""]}
[11:53:09AM] Worker 206.189.53.131:56644 disconnected.
[11:53:09AM] Nonce 1a released.
``` 

As you can see, a JsonSerializationException occurs for the id field because an integer is expected instead of the transmitted string. I suspect that this is a problem with the subscribeMethod of the websocket server. 

**But since it works without a proxy I'm not sure if it could be the proxy itself. Can someone take a look at this and possibly confirm the bug or the reason?**

**Comment by MarcoCiaramella** [comment]
hello @M-Kleinschmidt  thanks a lot for your message. So the main problem described is the ban from stratum pool because of too many connection. You don't need to use a proxy I can implement your suggestion in the websocket endpoint asap

**Comment by M-Kleinschmidt** [comment]
hey @MarcoCiaramella that would of course be the best solution if the same requests are bundled by your backend. Exactly because some pools have a limit of workers, e.g. MoneroOcean has a limit of 500 workers, as far as I know. The limit exists for different reasons, for example because every single connection produces workload for the mining pool.

I'll wait and see, thank you very much for your help. You are welcome to keep us updated here about the progress of the implementation.

**Comment by M-Kleinschmidt** [comment]
Sorry, didn't mean to close it

**Comment by MarcoCiaramella** [comment]
@M-Kleinschmidt I've just deployed the changes. The middle endpoint open one connection for the same stratum config and not for each connected machine as you suggested. Thanks for your contribution!
